### ISSUE TITLE
Periodic behaviours

### ISSUE THREAD

**Issue by luisns** [cjimison/barrage#36]
Have a way to define behaviours that run every X seconds.  For example: check inbox every 30 seconds.

**Comment by cjimison** [comment]
I am not sure if we want this.  It will break the whole tree traversal in that you kind of have an "event" that will trigger.  Don't get me wrong, I can see where it could be helpful but I can also see it breaking the meta logic of the Behavior tree.  For such a need I would create ordered node that has two children, a ordered node that will execute with a min time of 30 seconds and second child node that will run after 30 seconds.
